apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-ZenNavigator-settings
spec:
  forms:
    - group: basics
      label: 基本设置
      formSchema:
        - $el: a
          attrs:
            href: "https://docs.lik.cc"
            class: "py-4 block"
            target: "_blank"
            style:
              color: "#1890ff"
              fontSize: "0.875em"
              display: "flex"
              align-items: "center"
          children:
            - $el: span
              children: "查看 智阅GPT 帮助文档"
            - $el: img
              attrs:
                src: "/plugins/ZenNavigator/assets/static/img/link.svg"
                width: "14px"
                height: "14px"
                style:
                  margin-left: "4px"
        - $el: span
          children: "Halo插件主题交流群"
        - $el: div
          attrs:
            style:
              display: "flex"
              gap: "8px"
              marginTop: "8px"
          children:
            - $el: a
              attrs:
                href: "https://qm.qq.com/q/mPJeUOtG5G"
                target: "_blank"
                style:
                  color: "#1890ff"
                  fontSize: "0.875em"
                  padding: "4px 8px"
                  backgroundColor: "#f0f8ff"
                  borderRadius: "4px"
                  textDecoration: "none"
                  border: "1px solid #d1e7ff"
              children: "加入群聊 766203360"
            - $el: button
              attrs:
                type: "button"
                onclick: "navigator.clipboard.writeText('766203360').then(() => alert('群号已复制到剪贴板'))"
                style:
                  color: "#1890ff"
                  fontSize: "0.875em"
                  padding: "4px 8px"
                  backgroundColor: "#f0f8ff"
                  borderRadius: "4px"
                  border: "1px solid #d1e7ff"
                  cursor: "pointer"
              children: "复制群号"
        - $formkit: text
          label: 导航标题
          name: navTitle
          id: navTitle
          key: navTitle
          value: "Handsome主页导航"
          help: "导航名称"
        - $formkit: attachment
          label: 导航Logo
          name: navLogo
          id: navLogo
          key: navLogo
          value: "https://www.lik.cc/upload/logo.png"
          help: "网站顶部logo"
        - $formkit: attachment
          label: 导航背景
          name: bgImages
          id: bgImages
          key: bgImages
          value: "https://img-baofun.zhhainiao.com/pcwallpaper_ugc/preview/9b09b3e56cc7abc842f2985bafdc4c74_preview.mp4"
          help: 为空默认白色背景，支持视频背景和图片
        - $formkit: range
          name: transparency
          id: transparency
          key: transparency
          label: '背景蒙层透明度'
          value: 30
          min: 0
          step: 1
          max: 100
          help: $get(transparency).value
        - $formkit: checkbox
          label: 开启灵动岛弹窗
          name: enableSmart
          id: enableSmart
          key: enableSmart
          value: true
          help: "开启后会在导航页面增加一个灵动弹窗"
        - $formkit: code
          if: "$get(enableSmart).value === true"
          name: content
          label: 灵动岛弹窗
          value: ""
          language: html
          height: 200px
          help: 为空默认为欢迎语，支持 html 语法。
        - $formkit: checkbox
          label: 关闭版权声明
          name: disableCopyright
          id: disableCopyright
          key: disableCopyright
          value: false
          help: 关闭后将隐藏页脚中的作者版权信息